version: "3.9"
services:
  app:
    image: seanscraft/com.mihuatuanzi.backend.app:dev
    volumes:
      - .:/var/www/app
  cache:
    hostname: backend.cache.mihuatuanzi.io
    image: redis:latest
    volumes:
      - cache:/data

volumes:
  cache:
    driver: local
