version: "3.9"
services:
  app:
    image: seanscraft/com.mihuatuanzi.backend.app:dev
    volumes:
      - .:/home/app_user/app
  ingress:
    environment:
      APP_ENV: dev
  cache:
    hostname: backend.cache.mihuatuanzi.io
    image: redis:latest
    expose:
      - 6379
    volumes:
      - cache:/data
    networks:
      - backend.mihuatuanzi.io
