version: "3.9"
services:
  app:
    hostname: backend.app.mihuatuanzi.io
    image: seanscraft/com.mihuatuanzi.app:latest
    build:
      context: .
      target: app
    depends_on:
      - cache
    environment:
      env: prod
    networks:
      - default
  ingress:
    hostname: backend.ingress.mihuatuanzi.io
    image: seanscraft/com.mihuatuanzi.ingress:latest
    build:
      context: .
      target: ingress
    expose:
      - "80"
    networks:
      - default

volumes:
  cache:
    driver: local

networks:
  default:
    name: backend.mihuatuanzi.io
    external: true
