version: "3.9"
services:
  app:
    image: seanscraft/com.mihuatuanzi.www:latest
    build:
      context: .
      target: app
    depends_on:
      - cache
    environment:
      env: prod
    networks:
      - default
  cache:
    image: redis:latest
    expose:
      - 6379
    volumes:
      - cache:/data
    networks:
      - default

volumes:
  cache:
    driver: local
