version: "3.9"
services:
  app:
    hostname: backend.app.mihuatuanzi.io
    image: seanscraft/com.mihuatuanzi.backend.app:latest
    build:
      context: .
      target: app
    deploy:
      update_config:
        order: start-first
    depends_on:
      - cache
  proxy:
    hostname: backend.proxy.mihuatuanzi.io
    image: seanscraft/com.mihuatuanzi.backend.proxy:latest
    build:
      context: .
      target: ingress
    deploy:
      update_config:
        order: start-first
